
version: "3"
services:
  netflixdata:
    image: data-netflix-d
    ports:
      - "8086:8086"
    networks:
      - hasher1
    depends_on:
      - datamysql

  datamysql:
    image: mysql:8.0
    networks:
      - hasher1
    environment:
      - MYSQL_ROOT_PASSWORD=ankitasdm2020
      - MYSQL_DATABASE=netflixdata

networks:
   hasher1:




















